version: "3.9"
services:

  redis:
    image: "redis:alpine"
    ports:
        - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - . :/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env

    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  celery:
    restart: always
    build: .
    command: celery -A config.celery worker -l INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379
      - CELERY_BACKEND=redis://redis:6379
    depends_on:
      - web
      - redis
      - db
volumes:
  postgres_data: